#!/bin/bash
i=1
dossier_entree=$(cat $HOME/.gallery.ini | grep dossier_entree | awk -F ' ' '{ print $2}')
dossier_sortie=$(cat $HOME/.gallery.ini | grep dossier_sortie | awk -F ' ' '{ print $2}')

new_photo=false

while [[ i>0 ]]; do
	#statements

#echo Mes images
liste_fichiers=$(ls $dossier_entree)

for fichier in $liste_fichiers
do


	var1=$(exif $dossier_entree/$fichier | grep -m 1 "Date et" | awk -F '|' '{ print $2}')

	# pas  dexif sur la photo
	if [[ $var1 == "" ]];
		then
			repAlbum="nondate"
		else
			annee=$(echo $var1 | cut -c1-4)
			mois=$(echo $var1 | cut -c6-7)
			jour=$(echo $var1 | cut -c9-10)
			repAlbum=$annee"-"$mois"-"$jour
	fi




	md5image=$(md5sum $dossier_entree/$fichier | awk '{print $1}')
	mkdir -p $dossier_sortie"/"$repAlbum"/mini"
	cp $dossier_entree"/"$fichier $dossier_sortie"/"$repAlbum
	md5imagesorti=$(md5sum $dossier_sortie"/"$repAlbum"/"$fichier | awk '{print $1}')
	convert $dossier_sortie"/"$repAlbum"/"$fichier -resize "300x" $dossier_sortie"/"$repAlbum"/mini/"$fichier


	if [ $md5image = $md5imagesorti ]
	then
			new_photo=true
			echo Import réussi : $fichier
			rm $dossier_entree"/"$fichier
			
	else
			echo "Import échoué : $fichier"
			rm "$dossier_sortie/$repAlbum/$fichier"
	fi


	done

	if [ $new_photo == true ]
	then	
		echo mise à jour html
		./generation_html/genhtml.sh $dossier_sortie 
	fi
	  new_photo=false
	sleep 20
# while
done



exit 0
